---
title: "real data analysis"
author: "SDMLAB"
date: "\today"
output:
  html_document:
    df_print: paged
  pdf_document:
    includes:
      in_header: Markdown.tex
fontsize: 12
editor_options:
  chunk_output_type: console
---

```{r include=FALSE}
rm(list = ls())
source("sphereBox1.R")
source("quad_ISS-v3 - temp_JK.R")
source("splineBox1.9.R")
library(rgl)
library(sphereplot)
library(knitr)
library(Directional)
library(argosfilter)
knit_hooks$set(webgl = hook_webgl)
knitr::opts_chunk$set(echo = FALSE, cache = TRUE, cache.lazy = FALSE,
                      warning = FALSE)
```

# Set dataset 
```{r, webgl = TRUE}
data = readLines("dataset_cyclone.txt")
df1 <- strsplit(data, " ")
df1[[1]]
cyclone_list = data.frame(name = '0', row_count = '0', i = '0', id = '0')
cyclone_list$name = as.character(cyclone_list$name)
cyclone_list$row_count = as.numeric(cyclone_list$row_count)
cyclone_list$i = as.numeric(cyclone_list$i)
cyclone_list$id = as.character(cyclone_list$id)

for(i in 1:length(df1))
{
   if ((df1[[i]][1] == '66666') & (df1[[i]][23] == ""))
   {
      a = c(as.character(df1[[i]][14]), as.character(df1[[i]][5]), as.character(i),as.character(df1[[i]][2]) )
   cyclone_list = rbind(cyclone_list, a)
   }
      if ((df1[[i]][1] == '66666') & (df1[[i]][23] != ""))
   {
      a = c(as.character(df1[[i]][23]), as.character(df1[[i]][4]), as.character(i),as.character(df1[[i]][2]) )
   cyclone_list = rbind(cyclone_list, a)
   }
}
```

```{r}
cyclone_list$row_count[cyclone_list$id == '1516'] ##row count
index = as.numeric(cyclone_list$i[cyclone_list$id == '1516'])
df1[[index]]

```

```{r}
data_list = data.frame(time = 99999, long = 99999, lat = 99999, grade = 99999, 
                       central_press = 9999, wind_speed = 99999, direction_50 = 99999, 
                       long_radius_50 = 99999, short_radius_50 = 99999,direction_30 = 99999, 
                       long_radius_30 = 99999, short_radius_30 = 99999)
data_list$time = as.numeric(data_list$time)
data_list$lat = as.numeric(data_list$long)
data_list$long = as.numeric(data_list$lat)
data_list$grade = as.numeric(data_list$grade)
data_list$central_press = as.numeric(data_list$central_press)
data_list$wind_speed = as.numeric(data_list$wind_speed)
data_list$direction_50 = as.numeric(data_list$direction_50)
data_list$long_radius_50 = as.numeric(data_list$long_radius_50)
data_list$short_radius_50 = as.numeric(data_list$short_radius_50)
data_list$direction_30 = as.numeric(data_list$direction_30)
data_list$long_radius_30 = as.numeric(data_list$long_radius_30)
data_list$short_radius_30 = as.numeric(data_list$short_radius_30)


for(i in 2:62)
{
   a = c(as.numeric(df1[[index + (i-1)]][1]), as.numeric(df1[[index + (i-1)]][5])*0.1, as.numeric(df1[[index + (i-1)]][4])*0.1, as.numeric(df1[[index + (i-1)]][3]), as.numeric(df1[[index + (i-1)]][7]), as.numeric(df1[[index + (i-1)]][12]), 
as.numeric(df1[[index + (i-1)]][17]) %/% 10000, as.numeric(df1[[index + (i-1)]][17]) - (10000 * as.numeric(df1[[index + (i-1)]][17]) %/% 10000), as.numeric(df1[[index + (i-1)]][18]), as.numeric(df1[[index + (i-1)]][19]) %/% 10000, as.numeric(df1[[index + (i-1)]][19]) - (10000 * as.numeric(df1[[index + (i-1)]][19]) %/% 10000), as.numeric(df1[[index + (i-1)]][20]))
   data_list = rbind(data_list, a)
}
data_list = data_list[-1,]
data_list$central_press[1:5] = c(1006, 1004, 1002, 1002, 1000) 

data_list$wind_speed[5] = 35
data_list$short_radius_50[5] = 0
data_list$direction_30[5] = 9
data_list$short_radius_30[5] = 60

```




```{r}
time_range = range(data_list$time)
spherical_data = matrix(0, ncol = 3, nrow = nrow(data_list))
spherical_data[, 1] = data_list$time
#### time interval
for (i in 2:nrow(data_list))
{
   spherical_data[i,1] = data_list[i,1] - data_list[i-1,1]
   if (spherical_data[i, 1] == 82)
   {
      spherical_data[i,1] = spherical_data[i-1, 1] + 6
   }
   else if (spherical_data[i, 1] == 79)
   {
      spherical_data[i,1] = spherical_data[i-1, 1] + 3
   }
   else 
    spherical_data[i,1] = spherical_data[i-1, 1] + data_list[i,1] - data_list[i-1,1]  
}


spherical_data[,1]
time_range = range(spherical_data[,1])
spherical_data[, 1] = (spherical_data[, 1] - time_range[1]) / (time_range[2] - time_range[1])

spherical_data[,1]

plot(spherical_data[,1], spherical_data[,1])

spherical_data[, 2] = (90-data_list$lat)* pi /180
spherical_data[, 3] = (data_list$long) * pi /180


r3_data = matrix(0, ncol = 3, nrow = nrow(data_list))

# radian 
cartesian_to_spherical(c(0, 0, 1.1)) ### north pole lat 90
spherical_to_cartesian(c(0,90))
spherical_to_cartesian(c(90,0))

for(i in 1:nrow(data_list))
{
   #r3_data[i, ] = c(cos(spherical_data[i,2]) * cos(spherical_data[i,1]), cos(spherical_data[i,2]) * sin(spherical_data[i,1]), sin(spherical_data[i,2]))
   r3_data[i, ] = spherical_to_cartesian(spherical_data[i,2:3])
}

```

# Plot $y_n$ 
```{r echo=FALSE, wedgl = TRUE}
number_grid = 100
theta = seq(0, pi, length = number_grid)
phi = seq(0, 2 * pi, length = number_grid)
theta_phi = expand.grid(theta, phi)
grid_x = sin(theta_phi[, 1]) * cos(theta_phi[, 2])
grid_y = sin(theta_phi[, 1]) * sin(theta_phi[, 2])
grid_z = cos(theta_phi[, 1])
x_surf = matrix(grid_x, number_grid, number_grid)
y_surf = matrix(grid_y, number_grid, number_grid)
z_surf = matrix(grid_z, number_grid, number_grid)
open3d()
surface3d(x_surf, y_surf, z_surf, col = "light grey", alpha = 0.7)
# lines3d(rbind(c(0, 0, -1), c(0, 0, 1)))
texts3d(0,  0, 1.1, texts = "North pole")
#texts3d(cp[1, ], texts = "cp1")
#texts3d(cp[2, ], texts = "cp2")
test = spherical_to_cartesian(c(90-33,124) * pi /180)
test2 = spherical_to_cartesian(c(90-33.35,130)* pi /180)
text3d(test, texts = 'korea')
text3d(test2, texts = 'japan')
cartesian_to_spherical(c(0, -1 , 0))
spherical_to_cartesian(c(pi,0))

pch3d(r3_data, col = "black", cex = 2, pch = 19)
#lines3d(f, col = "blue", lwd = 5)
#arrow3d(0, true_mean, col = "red")
rglwidget()
```

# Fit linear spherical spline 
```{r}
### 31 must
source("quad_ISS-v3 - temp_JK.R")

t = spherical_data[, 1]
dimension = 15
# dim1 = 13
# dim2 = 15
# dimension = dim1+dim2
# initial_knots1 = s_knots_quantile(t[1:24], dimension = dim1)
# initial_knots1[dim1] = initial_knots1[dim1] - 1e-05
# initial_knots2 = s_knots_quantile(t[31:69], dimension = dim2)
# initial_knots2[1] = initial_knots2[1] + 1e-05
# initial_knots = c(initial_knots1, initial_knots2)
initial_knots = s_knots_quantile(t, dimension = dimension)
lambda_seq = exp(seq(log(1e-07), log(1), length = 40))

fit = penalized_linear_spherical_spline_temp(t = t, y = r3_data, 
                                             dimension = dimension,
                                             initial_knots = initial_knots,
                                             lambdas = lambda_seq, verbose = T,
                                             epsilon_iter = 1e-04, step_size = 1, 
                                             jump_eps = 1e-03)

#debugonce(penalized_linear_spherical_spline_temp)
```


# Best model
```{r}
best_index = which.min(fit$bic_list)
best_index
open3d()
surface3d(x_surf, y_surf, z_surf, col = "grey", alpha = 0.5)
texts3d(0, 0, 1.1, texts = "North pole")
pch3d(r3_data, col = "black", cex = 0.2, pch = 19)
#lines3d(real_fitted, col = "red", lwd = 5)
#lines3d(f, col = "blue", lwd = 5)
lines3d(fit[[best_index]]$gamma, col = "red", lwd = 5)
pch3d(fit[[best_index]]$control_points, col = "blue", cex = 0.5, pch = 20)
test = spherical_to_cartesian(c(90-33,124) * pi /180)
test2 = spherical_to_cartesian(c(90-33.35,130)* pi /180)
text3d(test, texts = 'korea')
text3d(test2, texts = 'japan')
fit[[best_index]]$control_points
fit[[best_index]]$knots
fit[[best_index]]
#lines3d(fit[[20]]$gamma, col = "red", lwd = 5)
lambda_seq[best_index]
#fit[[1]]$knots
rglwidget()
```

# Save RData
```{r}
save.image(file = "fit1_atsani.RData")
```

